import type { FullBlogPost } from 'types';

export default {
  id: 'xxqBKey',
  author: 'Wim Barelds',
  title: 'Swinging in Style: Crafting a 3D Pendulum Animation with CSS',
  date: '2022-06-17T11:00:00.000Z',
  tags: ['CSS', 'Animation', '3D Graphics'],
  shortDescription:
    'Learn the art of creating a mesmerizing pendulum animation using CSS, starting with a 2D rendition and elevating it to a stunning 3D spectacle.',
  body: `
_Disclaimer: This content is generated by ChatGPT and provides insights into building a captivating pendulum animation with CSS._

# Swinging in Style: Crafting a 3D Pendulum Animation with CSS

## Introduction

In the realm of web animations, the pendulum holds a certain allure. In this tutorial, we'll embark on a journey to create a mesmerizing pendulum animation using pure CSS. We'll begin with a simple 2D pendulum and gradually elevate it to a stunning 3D masterpiece.

## The Art of 2D Pendulum Animation

Our adventure starts with the basics: a 2D pendulum. We'll explore the fundamentals of CSS animations and transforms to bring a swinging motion to life. This includes defining pivot points, using the 'transform' property, and crafting smooth animations.

## Ascending to 3D Elegance

With the 2D pendulum in our grasp, we'll step into the enchanting world of 3D. We'll leverage CSS's 3D transforms to add depth and realism to our animation. You'll discover how to create a lifelike swinging motion in three dimensions, making the pendulum dance in the digital realm.

## Conclusion

By the end of this journey, you'll have not only mastered the art of pendulum animation but also experienced the transition from 2D to 3D in CSS. This captivating effect can enhance the visual appeal of your web projects and leave a lasting impression on your audience.

Are you ready to swing in style with CSS? Let's get started!

---

*Stay tuned for more exciting CSS animation techniques in upcoming posts.*
`,
  comments: [
    {
      date: '2022-06-18T08:20:15.000Z',
      author: 'Jordan Ellis',
      message:
        "Wow, that's cool! The 3D effect on the pendulum is so lifelike. Great job with the CSS animations.",
    },
    {
      date: '2022-06-19T10:30:47.000Z',
      author: 'Morgan Fisher',
      message:
        'I tried to recreate this but my pendulum goes wonky. Any tips on getting the animation smooth?',
    },
    {
      date: '2022-06-20T12:45:33.000Z',
      author: 'Taylor Brooks',
      message: 'This is amazing! How did you manage to get such a realistic swing with just CSS?',
    },
    {
      date: '2022-06-21T14:30:22.000Z',
      author: 'Chris Martinez',
      message:
        "I'm impressed with how fluid and natural the pendulum movement is. It's mesmerizing to watch!",
    },
    {
      date: '2022-06-22T16:45:10.000Z',
      author: 'Riley Thompson',
      message:
        "The 3D effect is fantastic, but I'm having trouble with the perspective on different screen sizes. Any advice?",
    },
    {
      date: '2022-06-23T18:30:55.000Z',
      author: 'Sam Rivera',
      message:
        'Absolutely brilliant use of CSS! The 3D pendulum animation adds such a dynamic element to the webpage.',
    },
    {
      date: '2022-06-24T20:15:42.000Z',
      author: 'Alex Thompson',
      message:
        "This pendulum animation is just what I needed for inspiration. It's incredible what you can achieve with CSS3.",
    },
    {
      date: '2022-06-25T22:50:27.000Z',
      author: 'Dana Wright',
      message:
        "Really cool effect! It's projects like this that show the power and versatility of CSS animations.",
    },
    {
      date: '2022-06-26T09:35:19.000Z',
      author: 'Jamie Lane',
      message:
        'Loved the tutorial on how to create this! The 3D pendulum is such a creative and elegant touch.',
    },
    {
      date: '2022-06-27T11:55:09.000Z',
      author: 'Erin Davis',
      message:
        "The pendulum movement is so smooth and realistic. It's amazing that this is all done with CSS!",
    },
  ],
} as FullBlogPost;
